### ISSUE TITLE
Pageable object returns incorrect ordering using QueryDsl

### ISSUE THREAD

**Issue by PranavKuthe** [querydsl/querydsl#2195]
Hi All,
I want to know whether this is an issue related to QueryDsl or Spring.
I am calling below method to fetch me an pageable object.

Page<TaskDetail> pageList = null;
pageList = taskDetailsRepository.findAll(queryBuilder.getValue(), pageable);

this call's QueryDSL implementation in "QueryDslJpaRepository" 

it gets me the result but the data order received is incorrect.
At the backend below query gets executed:

Hibernate: 
select * from ( select taskdetail0_.task_id as task_id1_1_, taskdetail0_.action as action2_1_, taskdetail0_.ato_name as ato_name3_1_, 
taskdetail0_.change_type as change_t4_1_, taskdetail0_.created_by as created_5_1_, taskdetail0_.created_date as created_6_1_, 
taskdetail0_.last_updated_by as last_upd7_1_, taskdetail0_.last_updated_date as last_upd8_1_, taskdetail0_.owner as owner9_1_, 
taskdetail0_.product_family as product10_1_, taskdetail0_.status as status11_1_, taskdetail0_.task as task12_1_ 
from task_detail taskdetail0_ 
order by taskdetail0_.created_date desc ) 
where rownum <= ?

Now if i manually execute query it gives an incorrect order result, but if i do not execute rownum in last line the order is as expected. 

My Question is how can we fix the order including rownum clause to be executed.

Regards
Pranav

**Comment by Shredder121** [comment]
> At the backend below query gets executed:

Which database do you use?
What (Hibernate) Dialect do you use

Anyway, it's a little hard to find out where the issue lies, since I do know quite a bit about Spring Data, but not all the specifics.

**Comment by PranavKuthe** [comment]
Hi Thanks for your attention.
We are using Oracle as a database and dialect as "org.hibernate.dialect.OracleDialect".

Regards
Pranav

**Comment by PranavKuthe** [comment]
I think i got the issue.
This is an Data Issue. I figured it out that there were duplicate entries of data in database, which causes this to happen. I fixed the data by modifying createddate to unique createddate entries and then it worked fine.
But still question remains same .. in case exact createddate entries (may be rarest or rare scenario) it can cause this issue. Where plain query executed in oracle gives correct results where from QueryDsl will give different.

If my views are fine then you can close this issue.

Regards
Pranav

**Comment by Shredder121** [comment]
Ah, I see.
Well, as soon as the column in the order by clause is ordered, the remaining order is implementation dependent.
It can be insertion order in the database, or join occurrence, if you also join.
So in this case, the order would be correct, yes?
Glad it was resolved anyhow. :+1:

**Comment by PranavKuthe** [comment]
Hi, Even though issue has been closed , i would like to add one more observation which supports my previous observation.
Now instead of date , If i sort the query with non unique field, then querydsl result is different from that of resultset obtained by Oracle query.

For Example below two queries should produce same output and same sequence but it is not .
So issues still persist.

QueryDsl:

Hibernate:
select * from ( select taskdetail0_.task_id as task_id1_1_, taskdetail0_.action as action2_1_, taskdetail0_.ato_name as ato_name3_1_,
taskdetail0_.change_type as change_t4_1_, taskdetail0_.created_by as created_5_1_, taskdetail0_.created_date as created_6_1_,
taskdetail0_.last_updated_by as last_upd7_1_, taskdetail0_.last_updated_date as last_upd8_1_, taskdetail0_.owner as owner9_1_,
taskdetail0_.product_family as product10_1_, taskdetail0_.status as status11_1_, taskdetail0_.task as task12_1_
from task_detail taskdetail0_
order by taskdetail0_.a_name desc )
where rownum <= ?

Oracle Query:
select * from task_detail order by a_name desc;

Note: I have just changed the order by column name from date to a_name.

Regards
Pranav

**Comment by PranavKuthe** [comment]
Hi, does anybody have any solution on this ??

Regards
Pranav

**Comment by Shredder121** [comment]
Could you maybe make an SQLFiddle with an example schema?
I'm not quite seeing what the issue is, ordering (of non-orderby columns) is highly implementation dependent after the actual order clause is met.
I'll reopen, so we can discuss further.

**Comment by PranavKuthe** [comment]
Thanks...
SQL Fiddle details:
Please execute below schema and temporary data on LHS by selected Oracle 11g R2 

CREATE TABLE USER_TABLE
( 
  U_ID  NUMBER(10) PRIMARY KEY,
  U_FIRSTNAME  VARCHAR2(15) NOT NULL,
  U_LASTNAME  VARCHAR2(15) NOT NULL
);
INSERT INTO USER_TABLE values(1, 'Pranav', 'Kuthe');
INSERT INTO USER_TABLE values(2, 'Virat', 'Kohli');
INSERT INTO USER_TABLE values(3, 'John', 'Sena');
INSERT INTO USER_TABLE values(4, 'Sachin', 'Tendulkar');
INSERT INTO USER_TABLE values(5, 'Mike', 'Tison');
INSERT INTO USER_TABLE values(6, 'Albert', 'Einstein');
INSERT INTO USER_TABLE values(7, 'Tiger', 'Woods');
INSERT INTO USER_TABLE values(8, 'Tiger', 'Wooods');
INSERT INTO USER_TABLE values(9, 'aaa', 'xyz');
INSERT INTO USER_TABLE values(10, 'bbb', 'tyz');
INSERT INTO USER_TABLE values(11, 'ccc', 'Wooods');
INSERT INTO USER_TABLE values(12, 'ppp', 'kkk');
INSERT INTO USER_TABLE values(13, 'gg', 'jj');
INSERT INTO USER_TABLE values(14, 'gg', 'hu');
INSERT INTO USER_TABLE values(15, 'yt', 'ty');
INSERT INTO USER_TABLE values(16, 'yt', 'po');
INSERT INTO USER_TABLE values(17, 'bbb', 'ty');



ON RHS please execute below queries:

Oracle Query:
SELECT * FROM USER_TABLE ORDER BY U_FIRSTNAME DESC;

QueryDSL Generated query:
select * from ( select user_table_0.U_ID as U_ID1_1, user_table_0.U_FIRSTNAME as U_FIRSTNAME2_1_, user_table_0.U_LASTNAME as U_LASTNAME3_1_
from USER_TABLE user_table_0 
order by user_table_0.U_FIRSTNAME desc ) 
where rownum <= 20;


Note: In Orderby clause i am sorting on basis of FIRSTNAME in both the queries.
But still i get different sequence of resultset.

I hope this address my concern.

**Comment by PranavKuthe** [comment]
Hi did you had any chance to look into above...

**Comment by shrds** [comment]
Hi @PranavKuthe, 

I am experiencing the similar issue with the Order By Clause when I use a String to Sort the results. I am using Projections to read only few columns and grouping by ParentId. It gives me wired results with groups broken into multiple with random number of children records when the Order By field has duplicate values in DB.
